#!/usr/bin/env bash
if [ "$1" == '-i' ] || [ "$1" == '--interactive' ]
then
	if ! which minicom &>/dev/null
	then
		echo "Please install minicom for interactive mode."
		exit 1
	fi
fi

if [ ! -e /dev/ttyACM0 ]
then
	echo "Waiting for /dev/ttyACM0 to exist..."
	while :
	do
		[ -e /dev/ttyACM0 ] && break
		sleep 1
	done
fi

if [ "$1" == '-i' ] || [ "$1" == '--interactive' ]
then
	minicom -b 115200 -o -D /dev/ttyACM0
else
	screen /dev/ttyACM0
fi
